using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text;
using OfflineFantasy.GameCraft.UI;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

namespace OfflineFantasy.GameCraft.Editors
{
    [CustomEditor(typeof(BasePanel), true)]
    public class PanelFieldsClassGenerator : Editor
    {
        private const string m_Prefix = "m_";

        private const string m_HeaderAttribute = "[Header(\"AutoGeneratedFields\")]";
        private const string m_SerializeFieldAttribute = "[SerializeField]";

        private Dictionary<Type, string> m_RequiredTypeList = new()
        {
            { typeof(Image), "Image" },
            { typeof(Button), "Button" },
            { typeof(Toggle), "Toggle" },
            { typeof(RectTransform), "RT" },
            { typeof(CanvasGroup), "CanvasGroup" },
#if ENABLE_TMP
            { typeof(TextMeshProUGUI), "TMP" },
#endif
        };

        private bool QueryCondition(GameObject _go)
        {
            return true;
        }

        private void GenerateFieldsScript()
        {
            var gos = OfflineFantasy.GameCraft.Utility.GameObjectUtility.GetChildGameObjectDict((target as BasePanel).gameObject, _condition: QueryCondition);

            StringBuilder fields = new(gos.Count);

            //fields.AppendLine($"\t\t{m_SerializeFieldAttribute}\n\t\tprivate {typeof(Canvas).FullName} m_Canvas;");

            int fieldIndex = 0;

            foreach (var go in gos.Values)
            {
                if (go.name.StartsWith(m_Prefix))
                {
                    foreach (var kv in m_RequiredTypeList)
                    {
                        if (go.TryGetComponent(kv.Key, out var component))
                        {
                            if (fieldIndex++ == 0)
                            {
                                fields.AppendLine($"\t\t{m_HeaderAttribute}");
                            }

                            fields.AppendLine($"\t\t{m_SerializeFieldAttribute}\n\t\tprivate {kv.Key.FullName} {GetFieldName(kv.Value, go.name)};");
                        }
                    }
                }
            }

            Type panelType = target.GetType();

            string codeContents = $@"using UnityEngine;

namespace {panelType.Namespace}
{{
    public partial class {panelType.Name}
    {{
{fields}
    }}
}}
";

            var guidArray = AssetDatabase.FindAssets(panelType.Name);

            string scriptPath = string.Empty;

            foreach (var guid in guidArray)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);

                if (path.EndsWith($"{panelType.Name}.cs"))
                    scriptPath = Path.GetDirectoryName(AssetDatabase.GUIDToAssetPath(guid));
            }

            File.WriteAllText($"{scriptPath}\\{panelType.Name}.Fields.cs", codeContents, System.Text.Encoding.UTF8);

            AssetDatabase.Refresh();
        }

        private void BoundFields()
        {
            serializedObject.FindProperty("m_Canvas").objectReferenceValue = (target as BasePanel).gameObject.GetComponent<Canvas>();
            serializedObject.FindProperty("m_CanvasGroup").objectReferenceValue = (target as BasePanel).gameObject.GetComponent<CanvasGroup>();
            serializedObject.FindProperty("m_CanvasScaler").objectReferenceValue = (target as BasePanel).gameObject.GetComponent<CanvasScaler>();
            serializedObject.FindProperty("m_GraphicRaycaster").objectReferenceValue = (target as BasePanel).gameObject.GetComponent<GraphicRaycaster>();

            var gos = OfflineFantasy.GameCraft.Utility.GameObjectUtility.GetChildGameObjectDict((target as BasePanel).gameObject, _condition: QueryCondition);

            StringBuilder fields = new(gos.Count);

            foreach (var go in gos.Values)
            {
                if (go.name.StartsWith(m_Prefix))
                {
                    foreach (var kv in m_RequiredTypeList)
                    {
                        if (go.TryGetComponent(kv.Key, out var component))
                            serializedObject.FindProperty(GetFieldName(kv.Value, go.name)).objectReferenceValue = component;
                    }
                }
            }

            serializedObject.ApplyModifiedProperties();
        }

        private string GetFieldName(string _typeName, string _gameObjectName)
        {
            return $"{_gameObjectName}_{_typeName}";
        }

        public override void OnInspectorGUI()
        {
            base.OnInspectorGUI();

            if (GUILayout.Button("生成字段类"))
                GenerateFieldsScript();

            if (GUILayout.Button("绑定字段"))
                BoundFields();
        }

        public static string GetSourcePath([CallerFilePath] string path = "")
        {
            return path;
        }
    }
}